### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by BBAPepsiMan** [Lunastellia/LethalCorporation#1]
Hey, just played on Reshanta... or tried to at least.

Encountered some Mask Hornets outdoors, but for some reason they were invisible?
Not too hindering but still inconvenience enough.

Then there's the method of reaching main. Requiring a jetpack to make ANY profit on a moon is not exactly a welcome inclusion. I understand it might be within your vision for such, but not everyone will share such a vision. I recommend stepping stones of sorts.

**Comment by Lunastellia** [comment]
Hello, thank you for your message. 

- Regarding the bees, I will be updating the game today to fix that issue.

- As for the map design and the use of the jetpack, it is intentional. The moon is very small and this represents a significant part of the danger! However, I will consider an alternative, likely involving risky jumps + portable ladder to reach the entrance. (update soon)

**Comment by BBAPepsiMan** [comment]
1 is fixed. 2 is an excellent addition. Thank you
